[project]
name = "yahoo-history-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.1",
    "requests>=2.32.5",
    "typer[all]>=0.24.0",
    "yfinance>=1.2.0",
]

[project.scripts]
etf = "etf_downloader.cli:main"

[tool.uv]
package = true